server.port=8080
spring.application.name=conducirApi

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

################################################
#	Oracle
###############################################
#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
#spring.datasource.driverClassName=oracle.jdbc.driver.OracleDriver
#spring.datasource.username=ESC_CONDUCTOR
#spring.datasource.password=oracle

################################################
#	MySql local
###############################################
#spring.datasource.url=jdbc:mysql://localhost:3306/esc_conductor?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=

################################################
#	MySql server
###############################################
spring.datasource.url=jdbc:mysql://serverd1.mysql.database.azure.com:3306/esc_conductor?useSSL=false
spring.datasource.username=serverd1
spring.datasource.password=aZ123456